#!/bin/bash

# Will attempt to stop DarkStar on all nodes listed in a file.
#
# Requires the name of a file in $FILE that contains the IP addresses
# of all the hosts to check.  Use one IP per line with no spaces
# or additional characters. This script will call another script
# that should be located on each host. Its name and location are
# contained in the $SCRIPT variable.

FILE="/opt/Dev/scripts/configuration/nodes.txt"
SCRIPT="/opt/Dev/scripts/stop_ds"


echo ""
echo "Stopping DarkStar on the cluster..."
echo ""
NUM=0
while read LINE
do
	NODE[$NUM]=$LINE
	let "NUM++"
done < $FILE
for HOST in "${NODE[@]}"
do
	if [ "$HOST" = "localhost" ]; then
		echo "Status of $HOST:"
		$SCRIPT
		echo""
	else
		echo "Status of $HOST:"
		ssh -p 22 $HOST $SCRIPT
		echo""
	fi
done
