package com.cep.messaging.impls.gossip.node.state;

import java.util.concurrent.atomic.AtomicInteger;

/**
 * A unique version number generator for any state that is generated by the
 * local node.
 */

public class VersionGenerator {
	private static AtomicInteger version_ = new AtomicInteger(0);

	public static int getNextVersion() {
		return version_.incrementAndGet();
	}
}
