CREATE INDEX EVENT_FIELDS_IDX1 ON EVENT_FIELDS (FIELD_ID)
/

CREATE INDEX EXCEPTION_BLOCK_IDX1 ON EXCEPTION_BLOCK (EXCEPTION_ID, EXCEPTION_TYPE_ID, EXCEPTION_DATETIME)
/

CREATE INDEX EXCEPTION_BLOCK_DATA_IDX1 ON EXCEPTION_BLOCK_DATA (EXCEPTION_ID, EXCEPTION_TYPE_SCHEMA_ID)
/

CREATE INDEX EXCEPTION_EVENT_FIELDS_IDX1 ON EXCEPTION_EVENT_FIELDS (EVENT_ID, FIELD_ID)
/

CREATE INDEX EXCEPTION_EXEMPTION_IDX1 ON EXCEPTION_EXEMPTION_XM (EXCEPTION_ID, EXEMPTION_TYPE_ID)
/

CREATE INDEX EXCEPTION_REVIEW_IDX1 ON EXCEPTION_REVIEW (EXCEPTION_ID, EXCEPTION_STATUS_TYPE)
/

