set def off
set echo on
spool as_system.log

CREATE TABLESPACE BD 
  LOGGING 
  DATAFILE SIZE 100M AUTOEXTEND ON NEXT  100M MAXSIZE UNLIMITED 
  EXTENT MANAGEMENT LOCAL 
  SEGMENT SPACE MANAGEMENT  AUTO;
 
CREATE USER BD01
    IDENTIFIED BY BD01 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD01;
GRANT CREATE TABLE TO BD01;
GRANT CREATE SEQUENCE TO BD01;
GRANT CREATE TRIGGER TO BD01;

CREATE USER BD02
    IDENTIFIED BY BD02 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD02;
GRANT CREATE TABLE TO BD02;
GRANT CREATE SEQUENCE TO BD02;
GRANT CREATE TRIGGER TO BD02;

CREATE USER BD03
    IDENTIFIED BY BD03 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD03;
GRANT CREATE TABLE TO BD03;
GRANT CREATE SEQUENCE TO BD03;
GRANT CREATE TRIGGER TO BD03;

CREATE USER BD04
    IDENTIFIED BY BD04 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD04;
GRANT CREATE TABLE TO BD04;
GRANT CREATE SEQUENCE TO BD04;
GRANT CREATE TRIGGER TO BD04;

CREATE USER BD05
    IDENTIFIED BY BD05 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD05;
GRANT CREATE TABLE TO BD05;
GRANT CREATE SEQUENCE TO BD05;
GRANT CREATE TRIGGER TO BD05;

CREATE USER BD06
    IDENTIFIED BY BD06 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD06;
GRANT CREATE TABLE TO BD06;
GRANT CREATE SEQUENCE TO BD06;
GRANT CREATE TRIGGER TO BD06;

CREATE USER BD07
    IDENTIFIED BY BD07 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD07;
GRANT CREATE TABLE TO BD07;
GRANT CREATE SEQUENCE TO BD07;
GRANT CREATE TRIGGER TO BD07;

CREATE USER BD08
    IDENTIFIED BY BD08 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD08;
GRANT CREATE TABLE TO BD08;
GRANT CREATE SEQUENCE TO BD08;
GRANT CREATE TRIGGER TO BD08;

CREATE USER BD09
    IDENTIFIED BY BD09 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD09;
GRANT CREATE TABLE TO BD09;
GRANT CREATE SEQUENCE TO BD09;
GRANT CREATE TRIGGER TO BD09;

CREATE USER BD10
    IDENTIFIED BY BD10 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD10;
GRANT CREATE TABLE TO BD10;
GRANT CREATE SEQUENCE TO BD10;
GRANT CREATE TRIGGER TO BD10;

CREATE USER BD11
    IDENTIFIED BY BD11 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD11;
GRANT CREATE TABLE TO BD11;
GRANT CREATE SEQUENCE TO BD11;
GRANT CREATE TRIGGER TO BD11;

CREATE USER BD12
    IDENTIFIED BY BD12 DEFAULT TABLESPACE BD
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON BD 
    ACCOUNT UNLOCK;
GRANT CONNECT TO BD12;
GRANT CREATE TABLE TO BD12;
GRANT CREATE SEQUENCE TO BD12;
GRANT CREATE TRIGGER TO BD12;

CREATE TABLE RADAR_BD_LIST 
(
  SHCEMA_NAME VARCHAR2(20) NOT NULL 
, BD_NAME VARCHAR2(255) 
, CONSTRAINT RADAR_BD_LIST_PK PRIMARY KEY 
  (
    SHCEMA_NAME 
  )
  ENABLE 
);
ALTER TABLE RADAR_BD_LIST
ADD CONSTRAINT RADAR_BD_LIST_UK1 UNIQUE 
(
  BD_NAME 
)
ENABLE;
create public synonym RADAR_BD_LIST for RADAR_BD_LIST;
grant select on RADAR_BD_LIST to public;

spool off
