set def off
set echo on
spool as_system.log

CREATE TABLESPACE RADAR 
  LOGGING 
  DATAFILE SIZE 100M AUTOEXTEND ON NEXT  100M MAXSIZE UNLIMITED 
  EXTENT MANAGEMENT LOCAL 
  SEGMENT SPACE MANAGEMENT  AUTO;
 
CREATE USER RADAR
    IDENTIFIED BY radar DEFAULT TABLESPACE RADAR 
    TEMPORARY TABLESPACE TEMP
    QUOTA UNLIMITED 
    ON RADAR 
    ACCOUNT UNLOCK;
GRANT CONNECT TO RADAR;
GRANT CREATE TABLE TO RADAR;
GRANT CREATE SEQUENCE TO RADAR;
GRANT CREATE TRIGGER TO RADAR;

spool off
