SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL';

CREATE SCHEMA IF NOT EXISTS `symbols` DEFAULT CHARACTER SET latin1 ;
USE `symbols` ;

-- -----------------------------------------------------
-- Table `symbols`.`NYSE_TRADES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`NYSE_TRADES` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`NYSE_TRADES` (
  `TRADE_TIMESTAMP` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ,
  `EXCHANGE` VARCHAR(1) NULL DEFAULT NULL ,
  `SYMBOL_SUFFIX` VARCHAR(6) NULL DEFAULT NULL ,
  `SYMBOL_ROOT` VARCHAR(6) NULL DEFAULT NULL ,
  `SALE_CONDITION` VARCHAR(4) NULL DEFAULT NULL ,
  `TRADE_VOLUME` DECIMAL(9,0) NULL DEFAULT NULL ,
  `TRADE_PRICE` DECIMAL(11,4) NULL DEFAULT NULL ,
  `TRADE_STOP_STOCK_INDICATOR` VARCHAR(2) NULL DEFAULT NULL ,
  `TRADE_CORRECTION_INDICATOR` VARCHAR(2) NULL DEFAULT NULL ,
  `TRADE_SEQUENCE_NUMBER` DECIMAL(16,0) NULL DEFAULT NULL ,
  `SOURCE_OF_TRADE` VARCHAR(1) NULL DEFAULT NULL ,
  `TRF` VARCHAR(1) NULL DEFAULT NULL )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `symbols`.`NYSE_TRADE_DATA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`NYSE_TRADE_DATA` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`NYSE_TRADE_DATA` (
  `DATE` VARCHAR(50) NULL DEFAULT NULL ,
  `TIME` VARCHAR(50) NULL DEFAULT NULL ,
  `MS` VARCHAR(50) NULL DEFAULT NULL ,
  `SYMBOL` VARCHAR(50) NULL DEFAULT NULL ,
  `EXCHANGE` VARCHAR(50) NULL DEFAULT NULL ,
  `SALE_CONDITION` VARCHAR(50) NULL DEFAULT NULL ,
  `VOLUME` BIGINT(50) NULL DEFAULT NULL ,
  `PRICE` DECIMAL(50,5) NULL DEFAULT NULL ,
  `STOP_IND` VARCHAR(50) NULL DEFAULT NULL ,
  `CORRECTION_IND` VARCHAR(50) NULL DEFAULT NULL ,
  `SEQUENCE_NUMBER` BIGINT(50) NULL DEFAULT NULL ,
  `TRADE_SOURCE` VARCHAR(50) NULL DEFAULT NULL ,
  `TRADE_REP_FAC` VARCHAR(50) NULL DEFAULT NULL ,
  `SYMBOL_ROOT` VARCHAR(50) NULL DEFAULT NULL ,
  `SYMBOL_SUFFIX` VARCHAR(50) NULL DEFAULT NULL ,
  INDEX `SYMBOL_DATA_SEQUENCE_NUMBER` (`SYMBOL` ASC, `DATE` ASC, `SEQUENCE_NUMBER` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `symbols`.`NYSE_TRADE_LOAD`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`NYSE_TRADE_LOAD` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`NYSE_TRADE_LOAD` (
  `N0528201` VARCHAR(50) NULL DEFAULT NULL ,
  `0` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_11-16` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_17-26` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_27-30` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_31-39` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_40-46` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_47-50` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_51-51` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_52-53` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_54-69` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_70-70` VARCHAR(50) NULL DEFAULT NULL ,
  `Field_71-71` VARCHAR(50) NULL DEFAULT NULL )
ENGINE = MyISAM
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `symbols`.`QUERY_ENTITY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`QUERY_ENTITY` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`QUERY_ENTITY` (
  `ENTITY_NAME` VARCHAR(20) NOT NULL ,
  `ENTITY_DESCRIPTION` VARCHAR(20) NULL DEFAULT NULL ,
  `ENTITY_QUERY_KEY` VARCHAR(20) NULL DEFAULT NULL ,
  `ENTITY_FIELD_DEFINITION` VARCHAR(20) NULL DEFAULT NULL ,
  `ENTITY_TYPE` VARCHAR(20) NULL DEFAULT NULL ,
  PRIMARY KEY (`ENTITY_NAME`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `symbols`.`QUERY_ENTITY_FIELDS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`QUERY_ENTITY_FIELDS` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`QUERY_ENTITY_FIELDS` (
  `FIELD_NAME` VARCHAR(20) NULL DEFAULT NULL ,
  `FIELD_TYPE` VARCHAR(20) NULL DEFAULT NULL ,
  `FIELD_LENGTH` INT(11) NULL DEFAULT NULL ,
  `FIELD_CLASS` VARCHAR(20) NULL DEFAULT NULL ,
  `FIELD_DEFINITION` VARCHAR(20) NULL DEFAULT NULL ,
  `FIELD_DESCRIPTION` VARCHAR(20) NULL DEFAULT NULL ,
  INDEX `idxQryEntity` (`FIELD_DEFINITION` ASC, `FIELD_NAME` ASC) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `symbols`.`TELESCOPE_USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`TELESCOPE_USER` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`TELESCOPE_USER` (
  `USER_NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `COMPANY_NAME` VARCHAR(45) NULL DEFAULT NULL ,
  `USER_EMAIL` VARCHAR(45) NULL DEFAULT NULL ,
  `USER_PASSWORD` VARCHAR(45) NULL DEFAULT NULL ,
  `USER_CELL_PHONE` VARCHAR(45) NULL DEFAULT NULL ,
  `USER_ROLE` VARCHAR(45) NULL DEFAULT NULL )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'This table stores the users for telescope' ;


-- -----------------------------------------------------
-- Table `symbols`.`nasdaq_security`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `symbols`.`nasdaq_security` ;

CREATE  TABLE IF NOT EXISTS `symbols`.`nasdaq_security` (
  `SYMBOL` VARCHAR(20) NOT NULL ,
  `COMPANY_NAME` VARCHAR(100) NULL DEFAULT NULL ,
  PRIMARY KEY (`SYMBOL`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
